[project]
name = "msc-warwick-capacities"
version = "0.1.0"
description = ""
authors = [
    {name = "ikercb2000",email = "ikercb2000@gmail.com"}
]
requires-python = ">=3.12,<3.15"
dependencies = [
    "commitizen (>=4.17.0,<5.0.0)",
    "capacities-ml-fin (==0.3.0)",
    "pandas (>=2.2.0,<3.0.0)",
    "numpy (>=2.0.0,<2.5.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pyarrow (>=25.0.1,<26.0.0)"
]


[tool.poetry]
packages = [{ include = "mwc_experiments", from = "src" }]
include = [
    { path = "configs/experiment_settings.toml", format = ["sdist", "wheel"] },
    { path = "configs/experiments.toml", format = ["sdist", "wheel"] },
    { path = "configs/experiments", format = ["sdist", "wheel"] },
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--basetemp=.pytest_tmp"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "openpyxl (>=3.1,<4.0)",
    "jupyterlab (>=4.2,<5.0)",
    "ipykernel (>=6.29,<8.0)",
    "pytest (>=8.0,<10.0)"
]
